### ISSUE TITLE
Recomedarions

### ISSUE THREAD

**Issue by TheComputerCat** [digitalautonomy/Jekyll-Onion-blog#10]
"Preparar la computadora vieja" titulo no relacionado al tema
Grafica de host and server
Comunicacion de cambios 
ip adr (hallar dir ip local)
Capturas de pantalla
no usar git, mejor usar CURL, menos pesado

contexto y pros/contras
juntar dos presentaciones
instrucciones
HOW TO USE TOR or Orbot
Como publico <---
Contexto dado por alguien del cad

**Comment by piratax007** [comment]
Issue without context.
