### ISSUE TITLE
Scripts for users

### ISSUE THREAD

**Issue by piratax007** [digitalautonomy/Jekyll-Onion-blog#3]
- [x] Develop script to manage:
  - [x] Add directory DEV with all developer stuff (scripts, etc.)
  - [x] Tor installation
  - [x] Tor permissions
  - [x] Torrc configuration
  - [x] Install Docker
  - [x] Clone Jekyll-Onion-blog
  - [x] Make Docker images from Docker file 
  - [x]  Docker launcher with needed tag
  - [x] Launch the Docker Container 
  - [x] Return Onion Service link
  - [x] Copy md files from user's computer to _i18n/en(es)/_posts into raspberry pi

**Comment by piratax007** [comment]
Please comment to update the current state of this issue.

**Comment by soleilzero** [comment]
Deleted scripts on commit 90adc3f0a2b414a6555f3c15b7c8877c81d30e55 because they were specific for Raspberry Pi, from what I understand only small changes are needed to make them for a regular Linux computer.

**Comment by piratax007** [comment]
done
