### ISSUE TITLE
Create an introduction and a list of materials

### ISSUE THREAD

**Issue by danilopedraza** [digitalautonomy/Jekyll-Onion-blog#5]
- [x] Establish a scheme for the instructions in README
    - [x] Create an introduction
    - [x] Create a list of materials
    - [x] Create a scheme of the OS installation process
    - [x] Create a scheme of the SSH connection
    - [x] Create a scheme of the blog creation and modification process
- [x] Fill the titles of the scheme (which are part of the introduction)

**Comment by piratax007** [comment]
Please update to delete all stuff related to Raspberry pi.

**Comment by danilopedraza** [comment]
I just did this in a commit tagged with issue #3.
