### ISSUE TITLE
Install and remote control instructions for normal computers

### ISSUE THREAD

**Issue by piratax007** [digitalautonomy/Jekyll-Onion-blog#6]
- [x] README
  - [x] Add commands to download repository
  - [x] SSH 
    - [x] Add information about how to set up SSH server
    - [x] Add information about how to set up SSH client
      - [ ] Windows
      - [x] Other GNU / Linux
      - [ ] MacOS

**Comment by piratax007** [comment]
Please comment to update the current state of this issue.

**Comment by soleilzero** [comment]
Deleted information about how to obtain a Debian installer, how to create a booteable USB for Debian installer and how to Install Debian as instructed.

**Comment by piratax007** [comment]
In order to have high levels of security features we do not recommend using windows or mac to manage the server machine in this project, our recommendation is to use Tails.
