### ISSUE TITLE
Complete instructions

### ISSUE THREAD

**Issue by danilopedraza** [digitalautonomy/Jekyll-Onion-blog#7]
- [ ] Complete materials section
- [ ] Complete Debian installation section
- [ ] Complete SSH setup section
- [ ] Complete blog creation and modification section

**Comment by piratax007** [comment]
Please comment to update the current state of this issue.

**Comment by danilopedraza** [comment]
Done.

**Comment by danilopedraza** [comment]
Closing since this is a duplicate of #6, except for the blog creation section.
